[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  pattern = "/(.*)(.pdf$)"
  to = "/"
  status = 403
  force = true

[[redirects]]
  from = "/gemini"
  to = "https://generativelanguage.googleapis.com/"
  status = 200
  force = true

[[redirects]]
  from = "/turbofely"
  to = "/npm/turbofely@1.0.0/src/turbofely.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://cdn.jsdelivr.net/:splat"
  status = 200
  force = true